"""initial migrations

Revision ID: 77751c7421f5
Revises: 
Create Date: 2020-04-07 23:51:14.343935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77751c7421f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dao_mu_bi_ji',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('chapter_nums', sa.String(length=64), nullable=True),
    sa.Column('chapter_title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dao_mu_bi_ji')
    # ### end Alembic commands ###
